name: Java CI with Maven

on:
  push:
    # Trigger the workflow on push to the main and develop branches
    branches: [ master ]
  pull_request:
    # Trigger the workflow on pull requests targeting the main and develop branches
    branches: [ master ]
    
jobs:
  build:
    # The job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      # This action checks out your repository code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      # This action sets up the specified Java version
      uses: actions/setup-java@v4
      with:
        java-version: '21' # Choose your required Java version
        distribution: 'temurin'
        cache: maven # Enables caching of Maven dependencies

    - name: Build with Maven
      # Runs the Maven command to clean, compile, and run tests
      run: mvn --batch-mode clean verify
